export const userConstants = {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
  SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',
  SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
  SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
  LOGOUT: 'USERS_LOGOUT'
};